version: '3.7'
services:
  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "./volumes/neo4j/data:/data"
    environment:
      - NEO4J_AUTH=neo4j/password
    user: "1000:1000"
