server:
  port: 8888
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
app:
  api-prefix: /api
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/identity/auth/**,
              ${app.api-prefix}/identity/users/**,
              ${app.api-prefix}/identity/roles/**,
              ${app.api-prefix}/identity/permissions/**
          filters:
            - StripPrefix=1
        - id: profile_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/profile/users/**
          filters:
            - StripPrefix=1
        - id: product_service
          uri: http://localhost:8083
          predicates:
              - Path=${app.api-prefix}/product/products/**,
                ${app.api-prefix}/product/categories/**,
                ${app.api-prefix}/product/template/products/**,
                ${app.api-prefix}/product/template/attributes/**,
          filters:
              - StripPrefix=1
services:
  base_url:
    identity:
        url: http://localhost:8081/identity
    profile:
        url: http://localhost:8082/profile
    product:
        url: http://localhost:8083/product
