server:
  port: 8081
service:
  name: identity
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/identity_service
    username: root
    password: 123456789
jwt:
  signerKey: oZ5aUBF9OoDbUccFmwnGp5mVwgDB8E4eU1/CtbpByh6A1r3HFlb6RBaUdTGKoy+PksCqtxsEMTVoTccL/SjO5Q==
  access-token-lifetime: 3600 # in second
  refresh-token-lifetime: 36000 # in seconds

profile-service:
  url: http://localhost:8082/profile
