package com.tuber.domain.valueobject.enums;

public enum Permissions {
    GET_USERS_INFO, CREATE_USER, UPDATE_USER, DELETE_USER,
    GET_ROLES, CREATE_ROLE, UPDATE_ROLE, DELETE_ROLE,
    GET_PERMISSIONS, REASSIGN_PERMISSION,
    GET_PRODUCT_CATEGORY, CREATE_PRODUCT_CATEGORY, UPDATE_PRODUCT_CATEGORY, DELETE_PRODUCT_CATEGORY,
    CREATE_TEMPLATE, UPDATE_TEMPLATE, DELETE_TEMPLATE,
    CREATE_WAREHOUSE, UPDATE_WAREHOUSE, GET_WAREHOUSE,
    TRANSFER_GOODS
}
