package com.tuber.domain.valueobject.enums;

public enum PermissionsDefault {
    CREATE_USER, UPDATE_USER, DELETE_USER,
    CREATE_ROLE, UPDATE_ROLE, DELETE_ROLE,
    CREATE_PERMISSION, UPDATE_PERMISSION, DELETE_PERMISSION,
    GET_AVAILABLE_DRIVERS, BOOK_RIDE, CANCEL_RIDE,
    GET_AVAILABLE_BOOKS, ACCEPT_RIDE
}
