package com.tuber.domain.valueobject.enums;

public enum PermissionsDefault {
    GET_USERS_INFO, CREATE_USER, UPDATE_USER, DELETE_USER,
    GET_ROLES, CREATE_ROLE, UPDATE_ROLE, DELETE_ROLE,
    GET_PERMISSIONS, CREATE_PERMISSION, UPDATE_PERMISSION, DELETE_PERMISSION,
    GET_AVAILABLE_DRIVERS, BOOK_RIDE, CANCEL_RIDE,
    GET_AVAILABLE_BOOKS, ACCEPT_RIDE
}
